channels:
  - pytorch
  - rdkit
  - conda-forge
dependencies:
  - cudatoolkit=11.6
  - python=3.8
  - pytorch=1.12.1
  - molsets=0.3.1
  - rdkit=2022.03.5
  - pandas=1.5.0
  - pip:
    - distance==0.1.3
    - pyyaml==5.4.1
    - tqdm==4.62.3
    - wget==3.2

